### ISSUE TITLE
OrbisGIS stops refreshing the geocatalogue

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisgis#1310] opened 2018-02-22 15:59 UTC
#### 1- Specifications 

* OrbisGIS version: 5.1
* Java version: 8
* Operating System: UBUNTU 17.10

#### 2- Expected behavior and actual behavior
The warning message "Update table state (100%)" appear on the lower right of OrbisGIS and I can not remove it. I can run SQL scripts, it does work (messages appear on the "Sortie" box that processed were run) but nothing happen on the GeoCatalogue. I try resfreshing it but is does not change.

**Comment by nicolas-f** [comment] 2018-02-23 09:31
Ouch
![image](https://user-images.githubusercontent.com/1382241/36587183-a8093880-1884-11e8-87c8-ed8c72c8c3d1.png)

**Comment by gpetit** [comment] 2018-04-04 14:10
@nicolas-f or @SPalominos any idea ?

**Comment by nicolas-f** [comment] 2018-05-16 07:22
I can't reproduce this issue anymore. May be it has been fixed by @SPalominos ?

**Comment by ebocher** [comment] 2018-05-16 07:26
So we close it.
Thanks a lot

**Closed as completed by ebocher** 2018-05-16 07:26 UTC
Labels: Bug, Severity Major

**Comment by SPalominos** [comment] 2018-05-17 07:15
@nicolas-f Not specific fix has been done for this issue, we should keep an eye on it and reopen the issue if it happens again
