### ISSUE TITLE
db corruption and other

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#1222] opened 2017-03-22 14:56 UTC
I have a really strange bug.
I'm working with the PPA release.
I launched my workspace in clean mode, then I executed the following SQL script:
```
drop table if exists test, test_edges, test_nodes, pts;
CREATE TABLE test(id INTEGER PRIMARY KEY, road LINESTRING, description VARCHAR,
                  way LINESTRING);
INSERT INTO test VALUES
('1','LINESTRING(0 0, 1 2)', 'road1', 'LINESTRING(1 1, 2 2, 3 1)'),
('2','LINESTRING(1 2, 2 3, 4 3)', 'road2', 'LINESTRING(3 1, 2 0, 1 1)'),
('3','LINESTRING(4 3, 4 4, 1 4, 1 2)', 'road3', 'LINESTRING(1 1, 2 1)'),
('4','LINESTRING(4 3, 5 2)', 'road4', 'LINESTRING(2 1, 3 1)');
SELECT ST_Graph('test');
SELECT * FROM test_nodes;
```
The process is ok. Wait few seconds (maybe 30) and then I have the following error message:
```
org.h2.jdbc.JdbcSQLException: File corrupted while reading record: "type: 1". Possible solution: use the recovery tool [90030-193]
```
Here I can not do anything in OG. Tables are freezed, .... So I stopped OG, removed the database.mv.db file and relaunched.
Same bug.
So I created a new workspace and try again : same bug

I start again this "protocole" and then it works. Great ! So I continue with
```
DROP TABLE test_nodes;
DROP TABLE test_edges;
SELECT ST_Graph('test', 'way');
-- Answer: TRUE

SELECT * FROM test_nodes;
```
It works I have my result in the output console and I can display in the map the table "COORDS". But after 1 or 2mn (during this time I don't touch OG), suddenly, I have the following error message

```
Cannot compute layer envelope:
The table "COORDS" does not contain a Geometry field, then the extent cannot be computed
Table "PTS" not found; SQL statement:
SELECT * FROM "PTS"  LIMIT 0 [42102-193]
Cannot compute layer envelope:
The table "COORDS" does not contain a Geometry field, then the extent cannot be computed
Table "PTS" not found; SQL statement:
SELECT COUNT(*) CPT  FROM "PTS"  [42102-193]
```
or
```
java.sql.SQLException: Table "COORDS" not found.
Cannot draw COORDS the table does not exists
Cannot compute layer envelope:
The table "COORDS" does not contain a Geometry field, then the extent cannot be computed
```

These two bugs are fully random, but I encountered them at least 5 times in 20mn !

Any idea @ebocher @SPalominos @nicolas-f ?

**Comment by ebocher** [comment] 2017-03-22 15:18
I will test.

**Comment by ebocher** [comment] 2017-03-22 15:22
I'm not able to reproduce... I'm using the last snapshot .

**Comment by gpetit** [comment] 2017-03-22 15:30
Hard to identify, but maybe I have something.
After the execution of the first block (until  ```SELECT * FROM test_nodes;```), reexecute once again ```SELECT * FROM test_nodes;``` --> here I have the corruption

**Comment by ebocher** [comment] 2017-03-28 14:03
I close this issue because I'm not able to reproduce the bug

**Closed by ebocher** 2017-03-28 14:03 UTC
Labels: Bug
