### ISSUE TITLE
Move the h2datasource.trace.db

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1188] opened 2017-03-01 20:08 UTC
A file is created by OrbisGIS to trace h2datasource errors...
The location of this file causes problem when OrbisGIS is deployed for example with and Ubuntu package.
What about moving this file into the ./OrbisGIS/version ?

**Comment by nicolas-f** [comment] 2017-03-02 07:54
We have to add a new default parameter on database uri:

http://h2database.com/html/features.html#trace_options

Tell h2 to use our SLF4j logging api:
```
jdbc:h2:~/test;TRACE_LEVEL_FILE=4
```

**Comment by ebocher** [comment] 2017-03-06 08:27
It seems it doesn't work.
Please @SPalominos could you confirm ?

**Comment by SPalominos** [comment] 2017-03-06 08:40
With the option `TRACE_LEVEL_FILE=4`, the content of the h2datasource.trace.db file is written in the log panel but the h2datasource.trace.db file still created and seems to be used to only display exception : [file content](http://pastebin.com/0cH2A35a)

**Comment by ebocher** [comment] 2017-03-08 09:08
@nicolas-f  any idea ?

**Comment by nicolas-f** [comment] 2017-03-08 09:10
Maybe ask help on h2 mailing list. Or find if there is switch in h2 source code.

**Comment by SPalominos** [comment] 2018-02-02 14:24
Issue posted on h2database github : h2database/h2database#833

**Comment by SPalominos** [comment] 2018-02-09 08:33
The issue is fixed on H2 side which do not catch the exception so it is OrbisGIS or H2GIS which is doing the catch.
With the fix, the H2 next release won't throw the exception anymore.

**Closed** 2018-12-13 11:00 UTC
Labels: Architecture - plugins, Enhancement, Request, Severity Normal
