### ISSUE TITLE
Style disappears when you have a big zoom in

### ISSUE THREAD

**Issue by mlecoeuvre** [orbisgis/orbisgis#704] opened 2014-07-08 09:36 UTC
When you have a style about a layer and you zoom  a lot, almost to the centimeter, the style disappears.

![capture du 2014-07-07 14 59 01](https://cloud.githubusercontent.com/assets/6450748/3507844/e5849fbe-0682-11e4-9a91-6580aa303e2b.png)

With a new zoom in the style disappears so the geometry too.
![capture du 2014-07-07 14 59 10](https://cloud.githubusercontent.com/assets/6450748/3507843/e584027a-0682-11e4-803a-4ce816b94862.png)

**Comment by gpetit** [comment] 2015-02-17 13:24
The problem is still there. For me it's more a problem of renderer.

**Comment by ebocher** [comment] 2016-02-05 15:28
Will be fixed with the new renderer.

**Comment by ebocher** [comment] 2020-11-05 15:34
Closed OrbisGIS UI dev stopped.

**Closed by ebocher** 2020-11-05 15:34 UTC
